"""Write RESULTS.md from the result files. Run from the repository root:
  python scripts/make_report.py
"""
import csv
import platform
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
RESULTS = ROOT / "results"
REF = RESULTS / "round-3-rebuilt"
POOLS = ("128m", "256m", "512m")
NAMES = ["partial-12-depth-1", "partial-12-depth-2", "partial-12-depth-3", "partial-12-depth-4",
         "partial-12-depth-6", "partial-12-depth-12", "sorted-medium-3", "overlap-medium-12",
         "sorted-15-target10", "overlap-1000-x-600"]
MINIMUM = dict(zip(NAMES, [1, 2, 3, 4, 6, 12, 3, 12, 15, 1000]))
ROUNDS = [  # label, directory, tag of the 128 MB runs
    ("round 1, binaries of 2026-09-28, data without fixed time origin", RESULTS / "round-1", "runs"),
    ("round 2, binaries of 2026-09-28, reproducible data", RESULTS / "round-2", "mem-128m"),
    ("round 3, rebuilt binaries, reproducible data", REF, "mem-128m"),
]


def summary(directory, tag):
    path = directory / f"summary-{tag}.tsv"
    if not path.exists():
        return {}
    return {(r["dataset"], r["variant"]): r for r in csv.DictReader(path.open(), delimiter="\t")}


def cell(r):
    if r["ok"].startswith("0/"):
        return f'fails ({r["ok"]})'
    text = f'{r["elapsed_med"]} ({r["elapsed_min"]}..{r["elapsed_max"]})'
    return text if r["ok"] == "10/10" else f'{text}, {r["ok"]} completed'


def times(pool):
    data = summary(REF, f"mem-{pool}")
    rows = ["| dataset | min groups | groups orig / mod | original | modified |",
            "|---|---|---|---|---|"]
    for n in NAMES:
        o, m = data[(n, "original")], data[(n, "accept-groups")]
        rows.append(f'| {n} | {MINIMUM[n]} | {o["groups"] or "-"} / {m["groups"]} '
                    f'| {cell(o)} | {cell(m)} |')
    return "\n".join(rows)


def spills():
    rows = ["| dataset | pool | sort | final aggregate | repartition | RSS MB |",
            "|---|---|---|---|---|---|"]
    show = lambda r, k: r[k] if r[k] != "" else "-"
    for n in NAMES:
        for pool in POOLS:
            data = summary(REF, f"mem-{pool}")
            o, m = data[(n, "original")], data[(n, "accept-groups")]
            rows.append(
                f'| {n} | {pool} | {show(o, "sort_spills")} → {show(m, "sort_spills")} '
                f'| {show(o, "final_agg_spills")} → {show(m, "final_agg_spills")} '
                f'| {show(o, "repartition_spills")} → {show(m, "repartition_spills")} '
                f'| {o["rss_mb_med"]} → {m["rss_mb_med"]} |')
    return "\n".join(rows)


def across_rounds(dataset):
    rows = ["| round | original | modified |", "|---|---|---|"]
    for label, directory, tag in ROUNDS:
        data = summary(directory, tag)
        if (dataset, "original") in data:
            rows.append(f'| {label} | {cell(data[(dataset, "original")])} '
                        f'| {cell(data[(dataset, "accept-groups")])} |')
    return "\n".join(rows)


def main():
    cpu = next(l.split(":", 1)[1].strip() for l in
               subprocess.run(["lscpu"], capture_output=True, text=True).stdout.splitlines()
               if l.startswith("Model name"))
    threads = subprocess.run(["nproc"], capture_output=True, text=True).stdout.strip()
    hashes = (REF / "binaries.sha256").read_text().strip()
    toolchain = (REF / "toolchain.txt").read_text().splitlines()
    patch = (REF / "accept-extra-groups.patch").read_text().strip()
    fd = (REF / "fd-limit/nofile-1024-accept-groups.err").read_text().splitlines()[0]

    (ROOT / "RESULTS.md").write_text(f"""# Extra file groups in DataFusion: original against modified (2026-09-29)

Generated by `scripts/make_report.py` from the result files under `results/`.

The reference results are those of round 3, measured with binaries rebuilt from a
recorded commit and a recorded patch. Rounds 1 and 2 used the binaries built on
2026-09-28, whose exact source is not recorded; they are kept for comparison and
reported separately at the end.

## Provenance of the binaries (round 3)

- Commit: e1aa7d956a5aa67452c9e8bd2a033599767055d8, clean detached worktree.
- Toolchain: {toolchain[0]}; {toolchain[-1]}.
- Build command, both binaries: `{(REF / "build-command.txt").read_text().strip()}`.
- `original`: the commit as it is. `accept-groups`: the commit plus
  `patch/accept-extra-groups.patch`, the only change:

```diff
{patch}
```

- SHA-256 (`results/round-3-rebuilt/binaries.sha256`):

```
{hashes}
```

- Plans checked before timing (`results/round-3-rebuilt/plan-check/`): the original has
  `SortExec` and at most `target_partitions` groups whenever more groups would be
  needed; the modified has no `SortExec`, the extra groups, `PartiallySorted([0, 1])`
  and `preserve_order=true`.

## Setup

- {cpu}, {threads} threads, Linux {platform.release()}.
- `--mem-pool-type fair`, `--memory-limit` 128m, 256m, 512m.
- `split_file_groups_by_statistics = true`; `target_partitions = 2`, except
  `sorted-15-target10` (10).
- Ten recorded runs per dataset, variant and pool size; one unrecorded warm-up;
  alternating order. Times are the `Elapsed` value of `EXPLAIN ANALYZE`, RSS from
  `/usr/bin/time`. Where runs failed, the median covers completed runs only and the
  number of completed runs is stated.

## Reproducing

From the repository root, with the Python packages of `requirements.txt` and the
two binaries built by `scripts/build_binaries.sh` in `bin/`:

    for d in 1 2 3 4 6 12; do python scripts/generate_partial_overlap.py --depth $d; done
    python scripts/generate_earlier_datasets.py
    for m in 128m 256m 512m; do
      python scripts/run_bench.py --runs 10 --memory $m --tag mem-$m \\
        --bin-dir bin --out results/round-3-rebuilt
    done
    python scripts/make_report.py

Seeds and the time origin (2026-09-29T00:00:00Z) are fixed; regenerating a dataset
gives byte-identical files (checked on depth 4). Datasets live in `/tmp/df-16919-*`.

## Files

- `results/round-3-rebuilt/`: patch, build logs, toolchain, SHA-256 of the binaries
  (the binaries themselves are not in the repository), plan check,
  `results-mem-<pool>.tsv` (every run), `summary-mem-<pool>.tsv`, `mem-<pool>/` (SQL,
  plans and stderr of every run), `fd-limit/`.
- `results/manifests/`: rows and per-column min/max of each file of the partial datasets.
- `results/round-2/`, `results/round-1/`: earlier rounds, with their own results.

## Datasets

Partial overlap: the same 600,000 rows in every dataset, 12 files, each sorted by
`(col_1, col_2)`. Depth d: file i overlaps files i+1 .. i+d-1 and is disjoint from
file i+d, so the minimum number of ordered groups is d. The groups produced can be
more: the algorithm starts from `target_partitions` empty groups, so depth 1
produces 2 groups although 1 would be enough. Overlap is built on `col_1`, because
the bounds of a file are assembled from per-column min/max.

The other four reproduce the cases of 2026-09-28: 3, 12, 15 and 1000 files in which
every file overlaps every other.

## Round 3: elapsed seconds, median (min..max)

### 128 MB

{times("128m")}

### 256 MB

{times("256m")}

### 512 MB

{times("512m")}

## Round 3: spill counts (original → modified, medians) and process RSS

{spills()}

No run spilled in the partial aggregate.

## Round 3: observations

1. Control: where both binaries produce 2 groups (depth 1 and 2), plans and times
   are the same.
2. The benefit depends on three things together: the ordering that is kept, the
   number of concurrent ordered streams, and the memory budget. At 128 MB, 3 and 4
   groups remove `SortExec` and the spills of the final aggregate. At 6 and 12
   groups the final aggregate spills again and most of the gain is lost. At 256 MB
   and 512 MB the same plans do not spill in the final aggregate.
3. Spilling, by operator, as the metrics show it:
   - Sort: no modified plan has a `SortExec`, so there are no sort spills.
   - Final aggregate: no spills in the modified plan with 3 and 4 groups at every
     pool size, and with 6, 12 and 1000 groups at 256 MB and 512 MB. At 128 MB it
     spills with 6, 12, 15 and 1000 groups, in some cases more often than in the
     original plan (12 fully overlapping files: 40 against 24; 1000 files: 82
     against 24). With 15 groups it spills at 128 MB and 256 MB.
   - `RepartitionExec` with `preserve_order=true`: spills in most modified plans,
     more with more groups and less with a larger pool. With 15 groups the count
     stays at about 150 at every pool size.
4. 1000 files: slower than the original at 128 MB, faster at 256 MB and 512 MB.
   Process RSS of the modified plan is about 1.7 GB at every pool size, against 0.5
   to 0.6 GB. Increasing the pool did not materially change the high process RSS.
   Which allocations make it up was not measured.
5. 15 files, target 10: the original fails at 128 MB and 256 MB in all runs and
   completes at 512 MB, where it is faster than the modified plan. With the modified
   plan an intermittent allocation failure was observed at 128 MB
   (`SortPreservingMergeExec`, which cannot spill).
6. `ulimit -n 1024`, 1000 files, modified plan: `{fd}`. This identifies the open
   that failed, a temporary file, not which files held the other descriptors. The
   CLI exits with status 0.
7. Not explained: depth 1 is slower than depth 2, with the same plan shape in both
   binaries.

## Across rounds, 128 MB

Rounds 1 and 2 are earlier observations with binaries of unrecorded source. They
agree with round 3 in direction; the sizes of two effects vary.

### 1000 files

{across_rounds("overlap-1000-x-600")}

The slowdown of the modified plan varies between rounds. It is not a stable
percentage.

### 15 files, target 10

{across_rounds("sorted-15-target10")}

A first execution of round 1, whose output was overwritten, showed 7 of 10
completed runs for the modified plan. That is a note, not a verifiable result.

## What this supports

Accepting extra groups can help under a limited pool, it introduces costs of its
own, and it does not dominate the original plan. This is evidence for discussing
how to choose the number of groups, not for removing the check unconditionally.
""")
    print(ROOT / "RESULTS.md")


if __name__ == "__main__":
    main()
