"""Write RESULTS.md from the result files. Run from the repository root:
  python scripts/make_report.py
"""
import csv
import platform
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
RESULTS = ROOT / "results"
REF = RESULTS / "round-4"
POOLS = ("128m", "256m", "512m")
NAMES = ["partial-12-depth-1", "partial-12-depth-2", "partial-12-depth-3", "partial-12-depth-4",
         "partial-12-depth-6", "partial-12-depth-12", "sorted-medium-3", "overlap-medium-12",
         "sorted-15-target10", "overlap-1000-x-600"]
MINIMUM = dict(zip(NAMES, [1, 2, 3, 4, 6, 12, 3, 12, 15, 1000]))
ROUNDS = [  # label, directory, tag of the 128 MB runs
    ("round 1, binaries of 2026-09-28, reporter's data without fixed time origin", RESULTS / "round-1", "runs"),
    ("round 2, binaries of 2026-09-28, reporter's data, fixed seed", RESULTS / "round-2", "mem-128m"),
    ("round 3, rebuilt binaries, reporter's data, fixed seed", RESULTS / "round-3-rebuilt", "mem-128m"),
    ("round 4, rebuilt binaries, this repository's generator", REF, "mem-128m"),
]


def summary(directory, tag):
    path = directory / f"summary-{tag}.tsv"
    if not path.exists():
        return {}
    return {(r["dataset"], r["variant"]): r for r in csv.DictReader(path.open(), delimiter="\t")}


def cell(r):
    if r["ok"].startswith("0/"):
        return f'fails ({r["ok"]})'
    text = f'{r["elapsed_med"]} ({r["elapsed_min"]}..{r["elapsed_max"]})'
    return text if r["ok"] == "10/10" else f'{text}, {r["ok"]} completed'


def times(pool):
    data = summary(REF, f"mem-{pool}")
    rows = ["| dataset | min groups | groups orig / mod | original | modified |",
            "|---|---|---|---|---|"]
    for n in NAMES:
        o, m = data[(n, "original")], data[(n, "accept-groups")]
        rows.append(f'| {n} | {MINIMUM[n]} | {o["groups"] or "-"} / {m["groups"]} '
                    f'| {cell(o)} | {cell(m)} |')
    return "\n".join(rows)


def spills():
    rows = ["| dataset | pool | sort | final aggregate | repartition | RSS MB |",
            "|---|---|---|---|---|---|"]
    show = lambda r, k: r[k] if r[k] != "" else "-"
    for n in NAMES:
        for pool in POOLS:
            data = summary(REF, f"mem-{pool}")
            o, m = data[(n, "original")], data[(n, "accept-groups")]
            rows.append(
                f'| {n} | {pool} | {show(o, "sort_spills")} → {show(m, "sort_spills")} '
                f'| {show(o, "final_agg_spills")} → {show(m, "final_agg_spills")} '
                f'| {show(o, "repartition_spills")} → {show(m, "repartition_spills")} '
                f'| {o["rss_mb_med"]} → {m["rss_mb_med"]} |')
    return "\n".join(rows)


def across_rounds(dataset):
    rows = ["| round | original | modified |", "|---|---|---|"]
    for label, directory, tag in ROUNDS:
        data = summary(directory, tag)
        if (dataset, "original") in data:
            rows.append(f'| {label} | {cell(data[(dataset, "original")])} '
                        f'| {cell(data[(dataset, "accept-groups")])} |')
    return "\n".join(rows)


def main():
    cpu = next(l.split(":", 1)[1].strip() for l in
               subprocess.run(["lscpu"], capture_output=True, text=True).stdout.splitlines()
               if l.startswith("Model name"))
    threads = subprocess.run(["nproc"], capture_output=True, text=True).stdout.strip()
    hashes = (REF / "binaries.sha256").read_text().strip()
    toolchain = (REF / "toolchain.txt").read_text().splitlines()
    patch = (REF / "accept-extra-groups.patch").read_text().strip()
    fd = (REF / "fd-limit/nofile-1024-accept-groups.err").read_text().splitlines()[0]

    (ROOT / "RESULTS.md").write_text(f"""# Extra file groups in DataFusion: original against modified

Generated by `scripts/make_report.py` from the result files under `results/`.

The reference results are those of round 4 (2026-10-02): binaries rebuilt from a
recorded commit and a recorded patch, datasets produced by the generator of this
repository. Rounds 1 to 3 (2026-09-29) measured datasets derived from the issue
reporter's generator, which this repository does not ship; rounds 1 and 2 also
used binaries whose exact source is not recorded. They are kept for comparison
and reported separately at the end.

## Provenance of the binaries (rounds 3 and 4)

- Commit: e1aa7d956a5aa67452c9e8bd2a033599767055d8, clean detached worktree.
- Toolchain: {toolchain[0]}; {toolchain[-1]}.
- Build command, both binaries: `{(REF / "build-command.txt").read_text().strip()}`.
- `original`: the commit as it is. `accept-groups`: the commit plus
  `patch/accept-extra-groups.patch`, the only change:

```diff
{patch}
```

- SHA-256 (`results/round-4/binaries.sha256`, the same files as in round 3):

```
{hashes}
```

- Plans checked before timing (`results/round-4/plan-check/`): the original has
  `SortExec` and at most `target_partitions` groups whenever more groups would be
  needed; the modified has no `SortExec`, the extra groups, `PartiallySorted([0, 1])`
  and `preserve_order=true`.

## Setup

- {cpu}, {threads} threads, Linux {platform.release()}.
- `--mem-pool-type fair`, `--memory-limit` 128m, 256m, 512m.
- `split_file_groups_by_statistics = true`; `target_partitions = 2`, except
  `sorted-15-target10` (10).
- Ten recorded runs per dataset, variant and pool size; one unrecorded warm-up;
  alternating order. Times are the `Elapsed` value of `EXPLAIN ANALYZE`, RSS from
  `/usr/bin/time`. Where runs failed, the median covers completed runs only and the
  number of completed runs is stated.

## Reproducing

From the repository root, with the Python packages of `requirements.txt` and the
two binaries built by `scripts/build_binaries.sh` in `bin/`:

    for d in 1 2 3 4 6 12; do python scripts/generate_partial_overlap.py --depth $d; done
    python scripts/generate_earlier_datasets.py
    for m in 128m 256m 512m; do
      python scripts/run_bench.py --runs 10 --memory $m --tag mem-$m \\
        --bin-dir bin --out results/round-4
    done
    python scripts/make_report.py

Seeds and the time origin (2026-09-29T00:00:00Z) are fixed; regenerating a dataset
gives byte-identical files (checked on depth 4, with and without the cached base
table). Datasets live in `/tmp/df-16919-*`.

## Files

- `results/round-4/`: patch, build logs, toolchain, SHA-256 of the binaries (the
  binaries themselves are not in the repository), plan check,
  `results-mem-<pool>.tsv` (every run), `summary-mem-<pool>.tsv`, `mem-<pool>/` (SQL,
  plans and stderr of every run), `fd-limit/`.
- `results/manifests/`: rows and per-column min/max of each file of the partial datasets.
- `results/round-3-rebuilt/`, `results/round-2/`, `results/round-1/`: earlier rounds
  on the reporter's data, with their own results.

## Datasets

Partial overlap: the same 600,000 rows in every dataset, 12 files, each sorted by
`(col_1, col_2)`. Depth d: file i overlaps files i+1 .. i+d-1 and is disjoint from
file i+d, so the minimum number of ordered groups is d. The groups produced can be
more: the algorithm starts from `target_partitions` empty groups, so depth 1
produces 2 groups although 1 would be enough. Overlap is built on `col_1`, because
the bounds of a file are assembled from per-column min/max.

The other four have files that all overlap each other: 3 files of 200,000 rows, 12
copies of the same 50,000 rows with a grouping column prefixed per copy, 15 files
of 40,000 rows with `target_partitions = 10` (the case of the issue), and 1000
files of 600 rows.

## Round 4: elapsed seconds, median (min..max)

### 128 MB

{times("128m")}

### 256 MB

{times("256m")}

### 512 MB

{times("512m")}

## Round 4: spill counts (original → modified, medians) and process RSS

{spills()}

No run spilled in the partial aggregate.

## Round 4: observations

1. Control: where both binaries produce 2 groups (depth 1 and 2), plans, times and
   spills are the same, and at 128 MB that shared plan already spills in the final
   aggregate (14 spills) and in the repartition (4). The data of this round is
   heavier for the ordered operators than the reporter's data of rounds 1 to 3:
   see `experiments/README.md` for the one variable that accounts for it, the
   length of the strings in `col_3` and `col_4`.
2. The benefit depends on three things together: the ordering that is kept, the
   number of concurrent ordered streams, and the memory budget. At 256 MB and
   512 MB, 3 to 6 groups bring the median from about 0.66-0.69 s to about
   0.38-0.40 s with no `SortExec` and no spills in the final aggregate. At 128 MB
   the same plans still spill in the final aggregate (16 spills with 3 and 4
   groups) and the gain is smaller: about 0.56-0.57 s against 0.75-0.78 s. With 12
   groups the gain shrinks with the pool: 0.387 against 0.650 s at 512 MB, 0.560
   against 0.661 s at 256 MB, 0.712 against 0.723 s at 128 MB.
3. Spilling, by operator, as the metrics show it:
   - Sort: no modified plan has a `SortExec`, so there are no sort spills.
   - Final aggregate: at 512 MB no modified plan spills. At 256 MB it spills with
     12 groups (5), with the 12 fully overlapping files (16) and with 15 groups
     (54). At 128 MB every modified plan spills: fewer times than the original
     with 3 to 6 groups (16 and 13 against 24-27), about as often with 12 groups
     (23 against 27), and more often with 1000 groups (87 against 28).
   - `RepartitionExec` with `preserve_order=true`: spills in most modified plans,
     more with more groups and less with a larger pool. With 15 groups the count
     stays at about 150 at every pool size, with the 12 fully overlapping files
     at 24.
4. 1000 files: slower than the original at 128 MB (0.886 against 0.832 s), faster
   at 256 MB and 512 MB (0.635 against 0.760 s, 0.669 against 0.728 s). Process RSS
   of the modified plan is 1.65 to 1.89 GB at every pool size, against 0.58 to
   0.66 GB. Which allocations make it up was not measured.
5. 15 files, target 10: the original fails at 128 MB and 256 MB in all runs. The
   modified plan fails at 128 MB in all runs too, in `SortPreservingMergeExec[0]`,
   the top-level merge, which cannot spill; at 256 MB it completes every run in
   0.343 s. At 512 MB both complete and here the modified plan is faster, 0.288
   against 0.325 s; in round 3, on the reporter's data, the original was faster at
   512 MB. The direction of this comparison depends on the data.
6. At 128 MB the original plan fails intermittently on every 12-file case in
   which it falls back to sorting: 9, 9, 9, 8, 8 and 4 completed runs out of 10
   (depth 3, 4, 6, 12, the 3 overlapping files, the 12 fully overlapping files),
   always with an allocation failure in `SortPreservingMergeExec[0]`. The modified
   plan completed every run of those cases. Reported as observed, without an
   estimate of the frequency.
7. `ulimit -n 1024`, 1000 files, modified plan: `{fd}`. This identifies the open
   that failed, a temporary file, not which files held the other descriptors. The
   CLI exits with status 0. The original completes under the same limit.
8. Not explained: depth 1 is slower than depth 2, with the same plan shape in both
   binaries (0.732 against 0.647 s at 128 MB).

## Across rounds, 128 MB

Rounds 1 to 3 measured datasets derived from the reporter's generator, with the
same cases and sizes; rounds 1 and 2 also used binaries of unrecorded source. The
comparison across rounds is therefore between datasets as well as between
binaries. The direction of the 1000-file result is the same in every round; its
size is not.

### 1000 files

{across_rounds("overlap-1000-x-600")}

The slowdown of the modified plan varies between rounds. It is not a stable
percentage.

### 15 files, target 10

{across_rounds("sorted-15-target10")}

A first execution of round 1, whose output was overwritten, showed 7 of 10
completed runs for the modified plan. That is a note, not a verifiable result.
On this round's data the modified plan fails in all runs at 128 MB and the
original completes at 512 MB more slowly than the modified plan; on the
reporter's data it completed 9 or 10 runs at 128 MB and was slower than the
original at 512 MB.

## What this supports

Accepting extra groups can help under a limited pool, it introduces costs of its
own, and it does not dominate the original plan. Which plan wins in a given case
depends on the memory budget, the number of ordered groups and the shape of the
data, including the width of the string columns. This is evidence for discussing
how to choose the number of groups, not for removing the check unconditionally.
""")
    print(ROOT / "RESULTS.md")


if __name__ == "__main__":
    main()
